# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PyDeluxeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from _typeshed import FileDescriptorLike
from typing import Self
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from PyQt6.QtWidgets import QWidget, QMainWindow,QMenuBar, QMenu,QFileDialog, QStatusBar, QToolBar,QListWidget
from PyQt6.QtGui import QIcon, QAction
from models import TextTabItem, Tabs
from api import Api
from util import *
from mainFunc import MainFunc       


class Ui_MainWindow(object):
            

    def autoLoadFile(self, filePath, hexView=False):
        self.main.autoLoadFile( filePath,hexView)
  
    def setMenu(self):
        menuBar = self.menu
        fileMenu = menuBar.addMenu('&File')
         # start with new
      
        fileMenu.addSeparator()

        newAction= QAction("&New",self.MainWindow)
        fileMenu.addAction(newAction)
        newAction.setShortcut("Ctrl+N")
        newAction.triggered.connect(self.main.showNewFileDialog)
        # then with open
        fileMenu.addSeparator()
        openAction = QAction("&Edit",self.MainWindow)
        fileMenu.addAction(openAction)
        openAction.setShortcut("Ctrl+O")
        openAction.triggered.connect(self.main.showOpenFileDialog)
        # then with hexview
        fileMenu.addSeparator()

        hexViewAction = QAction("&Hex View",self.MainWindow)
        fileMenu.addAction(hexViewAction)
        hexViewAction.setShortcut("Ctrl+H")
        hexViewAction.triggered.con0nect(self.main.doHexView)
       # then with saveas
        fileMenu.addSeparator()
  
        saveAsAction = QAction("Save As", self.MainWindow)
        saveAsAction.triggered.connect(self.main.showSaveAsDialog)
        fileMenu.addAction( saveAsAction  )   
        # then with save
        fileMenu.addSeparator()
  
        
        saveAction = QAction("&Save",self.MainWindow)
        fileMenu.addAction( saveAction  )   
        saveAction.triggered.connect(self.main.saveFile)
        saveAction.setShortcut("Ctrl+S")
        # then the rest
        fileMenu.addSeparator()
  
        registerAction= QAction("Register Shell Extensions",self.MainWindow)
        fileMenu.addAction( registerAction  )   
      
        registerAction.triggered.connect(self.main.registerShellExtesions)
       
        aboutAction= QAction("&About", self.MainWindow)
        fileMenu.addSeparator()
        fileMenu.addAction( aboutAction  ) 
        aboutAction.triggered.connect(self.main.showAbout)
 
        
        
        
        #newMenu = QMenu("&New",fileMenu)
        editMenu = QMenu("&Edit",fileMenu )
        saveMenu = QMenu("&Save",fileMenu)
        saveAsMenu = QMenu("Save As",fileMenu)
        registerMenu = QMenu("Register Shell Extensions",fileMenu)
        aboutMenu = QMenu("&About",fileMenu)
        

   ##   menuBar.addMenu(newMenu)
        menuBar.addMenu(editMenu)
        menuBar.addMenu(saveMenu)
        menuBar.addMenu(saveAsMenu)
        menuBar.addMenu(registerMenu)
        menuBar.addMenu(aboutMenu)
        
       # Creating menus using a QMenu object
      
       # Creating actions
         
        # setting shortcuts
        
        # adding actions
        #newMenu.addAction(newAction )
        editMenu.addAction(openAction )
        saveMenu.addAction( saveAction )
        saveAsMenu.addAction(saveAsAction)
        #newMenu.addAction(newAction )
        registerMenu.addAction(newAction )
        aboutMenu.addAction(aboutAction)
        
        # Creating connection between
        
        menuBar.show()

    def statusChanged(self,text):
        self.log.addItem(text)

    def setupUi(self):
        self.MainWindow=QMainWindow()
        self. MainWindow.setWindowTitle("DeluxeEdit")
        self.MainWindow.resize(798, 600)
        self.tabs=Tabs()
  
        
        self.MainWindow.setWindowIcon(QtGui.QIcon("deluxeedit.png"))
        
        self.statusBar=QStatusBar()
        
        self.MainWindow.setStatusBar(self.statusBar)
        
        
        self.statusBar.showMessage("Startup")

        self.statusBar.messageChanged.connect(self.statusChanged)
        self.main =MainFunc(self.statusBar,self.tabs)
        
        toolbar = QToolBar("Log")
        self.log = QListWidget()
        toolbar.addWidget(self.log)
        self.MainWindow.addToolBar(toolbar)
        
        self.MainWindow.setCentralWidget(self.tabs.tabFiles)
        self.menu=QMenuBar()
        self.MainWindow.setMenuBar (self.menu)
        self.setMenu()


        self.retranslateUi(self.MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyDeluxeEdit"))

    def __init__(self):
        super().__init__()
        self.setupUi()     
        self.MainWindow.show()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi()
    MainWindow.show()
    sys.exit(app.exec_())
