# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PyDeluxeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from PyQt6.QtWidgets import QWidget, QMainWindow,QMenuBar, QMenu,QFileDialog, QStatusBar, QToolBar,QListWidget
from PyQt6.QtGui import QIcon, QAction
from models import TextTabItem, Tabs
from api import Api
from util import *
from mainWidget import MainWidget       


class Ui_MainWindow(object):
            

    def autoLoadFile(self, filePath, hexView=False):
        self.mainWidget.autoLoadFile( filePath,hexView)
  
    def setMenu(self):
        menuBar = self.MainWindow.menuBar
        # Creating menus
        fileMenu = QMenu("&File")
        menuBar.addMenu(fileMenu)
      # Source - https://stackoverflow.com/questions/10200594/pyqt-basic-example-of-accessing-and-adding-a-submenu-to-an-existing-context-men
# Posted by Karnisov
# Retrieved 2025-11-06, License - CC BY-SA 3.0

        
        
        newMenu = QMenu(fileMenu)
        editMenu = QMenu(fileMenu )
        saveMenu = QMenu(fileMenu)
        saveAsMenu = QMenu(fileMenu)
        registerMenu = QMenu(fileMenu)
        aboutMenu = QMenu(fileMenu)
        
        newMenu.title="&New"
        editMenu.title="&Edit"
        saveMenu.title="&Save"
        saveAsMenu.title="Save As"
        registerMenu.title="Register Shell Extensions"
        aboutMenu.title="&About"

        menuBar.addMenu(newMenu)
        menuBar.addMenu(editMenu)
        menuBar.addMenu(saveMenu)
        menuBar.addMenu(saveAsMenu)
        menuBar.addMenu(registerMenu)
        menuBar.addMenu(aboutMenu)
        
       # Creating menus using a QMenu object
      
       # Creating actions
        newAction= QAction()
        aboutAction= QAction()
        registerAction= QAction()
        newAction.setShortcut("Ctrl+N")
        openAction = QAction()
        openAction.setShortcut("Ctrl+O")
        hexViewAction = QAction()
        hexViewAction.setShortcut("Ctrl+H")
        saveAction = QAction()
        saveAction.setShortcut("Ctrl+S")
        saveAsAction = QAction()
        
        # adding actions
        newMenu.addAction(newAction )
        editMenu.addAction(openAction )
        saveMenu.addAction(saveAction )
        saveAsMenu.addAction(saveAsAction)
        newMenu.addAction(newAction )
        registerMenu.addAction(newAction )
        aboutMenu.addAction(aboutAction)
        
        # Creating connection between
        newAction.triggered.connect(self.mainWidget.showNewFileDialog)
        menuBar.show()

    def statusChanged(self,text):
        self.log.addItem(text)

    def setupUi(self):
        self.MainWindow=QMainWindow()
        self. MainWindow.setWindowTitle("PyDeluxeEdit")
        self.MainWindow.resize(798, 600)
        self.tabs=Tabs()
  
        
        self.MainWindow.setWindowIcon(QtGui.QIcon("deluxeedit.png"))
        self.MainWindow.statusBar=QStatusBar()
        self.MainWindow.statusBar.messageChanged.connect(self.statusChanged)
 
        self.mainWidget =MainWidget(self.MainWindow.statusBar)
        
        toolbar = QToolBar("Log")
        log = QListWidget()
        toolbar.addWidget(log)
        self.MainWindow.addToolBar(toolbar)
        
        self.MainWindow.setCentralWidget(self.tabs.tabFiles)
        self.MainWindow.menuBar=QMenuBar()
        self.setMenu()


        self.retranslateUi(self.MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyDeluxeEdit"))

    def __init__(self):
        super().__init__()
        self.setupUi()     
        self.MainWindow.show()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi()
    MainWindow.show()
    sys.exit(app.exec_())
